### PR TITLE
Users, Teams and Permissions

### PR DESCRIPTION
**Pull request by egeldenhuys**
Please see the `auth.md` file.

#### erd 1
erd

We will discuss the feature here and update the document as we reach conclusions.

### CODE REVIEW

**Comment by egeldenhuys** [comment]
Disclaimer: I am not an expert when it comes to database design, if there are problems with my ERD please point them out and suggest a solution.

**Comment by FJMentz** [comment]
@egeldenhuys, What is the relationship a user has with Resource? (Wil specific users have access to some stacks/services and other not even-though they are part of the same team?)

**Comment by FJMentz** [comment]
With above question unclear, I would like to suggest these changes:

auth-erd

**Comment by egeldenhuys** [comment]
TODO: 
- [ ] Move roles to own table and associate with User

**Comment by FJMentz** [comment]
After discussion with @egeldenhuys, I've come to a new suggested erd.

auth-erd

**Comment by egeldenhuys** [comment]
Some things concepts to resolve: Global orientated roles vs team orientated roles.

Global: If a user can deploy, then they can deploy regardless of team.
Team: A team will have a leader that can manage the roles of users in the team. This will allow you to have people that are super users in one team, and guests in another team.

## Team Oriented
### Roles
#### Administrator
- No restrictions
- Create teams
- Create users
- Assign team leaders
- Assign users to teams
- Assign roles to users
- Can view all resources

#### Super User
- Can deploy stacks/services that use bind mounts

#### Normal User
- Cannot deploy stacks/services that use bind mounts

#### Guest
- Can only perform read only operations
- Cannot inspect (could give a away secrets in ENV variables)
- Cannot view logs (yes/no?)

#### Team Leader
- Can create users in teams where they are the leader
- Can only assign roles equal or less than own rank
- Remove users from team

### Visibility of resources
- If you are part of a team, you can view the resources in that team
- When deploying in a team, the member can choose the visibility of the resource
  - Team only or Public
  - When public everyone can see the resource from a guest perspective (Read Only)

### Permissions
Administrator, Super User, Normal User, guest can be condensed to using the following
permission hierarchy:
- admin (Administrator, no restrictions, **global**)
- bind (Able to use bind mounts when deploying)
- deploy (Can deploy if part of a team)
- inspect (Can use the inspect operation)
- logs (Can use the logs operation)

**Comment by devosray** [comment]
We might want to ask Compiax about how they would want to manage their teams/assign roles inside of Docks. I like the roles and permissions as laid out above; it makes sense from my viewpoint. We, however, do not have any experience with managing a team of developers deploying different stacks on a Docker swarm.

**Comment by egeldenhuys** [comment]
Guests should also be able to view logs.

**Comment by arneschreuder** [comment]
Hi Guys

I took a look at the proposed ERD. Seems fine for me. My 2c:

1. The purpose of a team is to restrict control over resources. For example team 1 can not alter team 2's stuff.
2. The purpose of roles is to define allowable actions in the application. For example, an admin can do everything, while a normal user can perhaps only start and stop a container. (You can implement ACL as you wish).

My suggestion would be:

First build the system without any ACL in mind. This is basically then just a frontend to the docker-cli.
Then when that is done, focus on roles and ACL
Then only focus on teams and resources, as this is a layer above the docker-cli

**Comment by egeldenhuys** [comment]
Thank you for the feedback.

For demo 3 we will only have an admin account and authentication on the Docks API
For demo 4 we will look into different account roles and teams

**Pull request merged**
